---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: install git, wget, tree, sudo, ufw on nodes
    apt:
     name: "{{ item }}"
     state: present
    with_items:
     - git
     - tree
     - wget
     - sudo
     - ufw